name: Deploy Site on Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: echo "${{ env.SSH_VARIABLE_USER }}"